### ISSUE TITLE
Auth Err

### ISSUE THREAD

**Issue by maggienj** [maggienj/Python2Twitter#1]
C:\mysoft\pysoft\py> python twitter_streaming.py
Traceback (most recent call last):
  File "C:\mysoft\pysoft\Anaconda3\lib\site-packages\twitter-1.17.1-py3.5.egg\twitter\stream.py", line 207, in handle_stream_response
  File "C:\mysoft\pysoft\Anaconda3\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\mysoft\pysoft\Anaconda3\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\mysoft\pysoft\Anaconda3\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\mysoft\pysoft\Anaconda3\lib\urllib\request.py", line 510, in error
    return self._call_chain(_args)
  File "C:\mysoft\pysoft\Anaconda3\lib\urllib\request.py", line 444, in _call_chain
    result = func(_args)
  File "C:\mysoft\pysoft\Anaconda3\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Authorization Required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "twitter_streaming.py", line 22, in <module>
    iterator = twitter_stream.statuses.sample()
  File "C:\mysoft\pysoft\Anaconda3\lib\site-packages\twitter-1.17.1-py3.5.egg\twitter\api.py", line 312, in **call**
  File "C:\mysoft\pysoft\Anaconda3\lib\site-packages\twitter-1.17.1-py3.5.egg\twitter\stream.py", line 284, in _handle_response
  File "C:\mysoft\pysoft\Anaconda3\lib\site-packages\twitter-1.17.1-py3.5.egg\twitter\stream.py", line 209, in handle_stream_response
twitter.api.TwitterHTTPError: Twitter sent status 401 for URL: 1.1/statuses/sample.json using parameters: (oauth_consumer_key=<<removed>>&oauth_nonce=<<removed>>&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1473827523&oauth_token=<<removed>>%22&oauth_version=1.0&oauth_signature=<<removed>>%3D)
details: <html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n<title>Error 401 Unauthorized</title>
</head>
<body>

<h2>HTTP ERROR: 401</h2>

<p>Problem accessing '/1.1/statuses/sample.json?oauth_consumer_key=<<removed>>............ Reason:

<pre>    Unauthorized</pre>

</body>
</html>

**Comment by maggienj** [comment]
Solved!
